// demo/vue3-javaex-editor-demo/src/App.vue
<template>
  <main class="demo-shell">
    <aside class="demo-sidebar">
      <div class="demo-brand">
        <p>Vue 3 示例</p>
        <h1>javaexEditor</h1>
      </div>
      <nav class="demo-nav" aria-label="示例页面">
        <a
          v-for="page in pages"
          :key="page.key"
          :href="`#${page.key}`"
          :class="{ 'is-active': page.key === currentPage.key }"
        >
          {{ page.title }}
        </a>
      </nav>
    </aside>

    <section class="demo-main">
      <component :is="currentPage.component" :key="currentPage.key" :page="currentPage" />
    </section>
  </main>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { pages } from "./pages/index.js";

const currentPageKey = ref(getHashPageKey());
const currentPage = computed(() => pages.find((page) => page.key === currentPageKey.value) || pages[0]);

onMounted(() => {
  window.addEventListener("hashchange", handleHashChange);
  if (!location.hash) {
    location.hash = "#default";
    currentPageKey.value = "default";
  } else {
    handleHashChange();
  }
});

onBeforeUnmount(() => {
  window.removeEventListener("hashchange", handleHashChange);
});

function handleHashChange() {
  currentPageKey.value = getHashPageKey();
}

function getHashPageKey() {
  return (location.hash || "#default").slice(1);
}
</script>

// demo/react-javaex-editor-demo/src/App.jsx
import { useEffect, useMemo, useState } from "react";
import { pages } from "./pages/index.js";

function getHashPageKey() {
  return (location.hash || "#default").slice(1);
}

export default function App() {
  const [pageKey, setPageKey] = useState(getHashPageKey);
  const currentPage = useMemo(() => pages.find((page) => page.key === pageKey) || pages[0], [pageKey]);
  const CurrentPage = currentPage.component;

  useEffect(() => {
    const onHashChange = () => setPageKey(getHashPageKey());
    window.addEventListener("hashchange", onHashChange);
    if (!location.hash) {
      location.hash = "#default";
      setPageKey("default");
    } else {
      onHashChange();
    }
    return () => window.removeEventListener("hashchange", onHashChange);
  }, []);

  return (
    <main className="demo-shell">
      <aside className="demo-sidebar">
        <div className="demo-brand">
          <p>React 示例</p>
          <h1>javaexEditor</h1>
        </div>
        <nav className="demo-nav" aria-label="示例页面">
          {pages.map((page) => (
            <a key={page.key} href={`#${page.key}`} className={page.key === currentPage.key ? "is-active" : ""}>
              {page.title}
            </a>
          ))}
        </nav>
      </aside>
      <section className="demo-main">
        <CurrentPage key={currentPage.key} page={currentPage} />
      </section>
    </main>
  );
}
