// demo/react-javaex-editor-demo/src/components/RichTextEditor.jsx
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef } from "react";
import { createEditor } from "javaex-editor";

function toHtmlString(value) {
  return value == null ? "" : String(value);
}

const RichTextEditor = forwardRef(function RichTextEditor(
  {
    value = "",
    onValueChange,
    onChange,
    onReady,
    editorId = "rich-text-editor",
    placeholder = "请输入内容",
    height = 520,
    maxHeight,
    toolbar,
    emojiGroups,
    editorOptions = {}
  },
  ref
) {
  const hostRef = useRef(null);
  const editorRef = useRef(null);
  const valueRef = useRef(toHtmlString(value));
  const callbacksRef = useRef({ onValueChange, onChange, onReady });
  const resolvedMaxHeight = maxHeight === undefined ? height : maxHeight;

  const stableEditorOptions = useMemo(() => editorOptions, [editorOptions]);

  useEffect(() => {
    callbacksRef.current = { onValueChange, onChange, onReady };
  }, [onValueChange, onChange, onReady]);

  useEffect(() => {
    if (!hostRef.current || editorRef.current) {
      return undefined;
    }

    const editorConfig = {
      ...stableEditorOptions,
      editorId,
      value: valueRef.current,
      placeholder,
      height,
      maxHeight: resolvedMaxHeight,
      onChange(payload) {
        const html = toHtmlString(payload?.html);
        valueRef.current = html;
        callbacksRef.current.onValueChange?.(html);
        callbacksRef.current.onChange?.(payload);
      }
    };

    if (Array.isArray(toolbar)) {
      editorConfig.toolbar = toolbar;
    }
    if (Array.isArray(emojiGroups) && emojiGroups.length) {
      editorConfig.emojiGroups = emojiGroups;
    }

    editorRef.current = createEditor(hostRef.current, editorConfig);
    callbacksRef.current.onReady?.(editorRef.current);

    return () => {
      editorRef.current?.destroy?.();
      editorRef.current = null;
    };
  }, [editorId, placeholder, height, resolvedMaxHeight, toolbar, emojiGroups, stableEditorOptions]);

  useEffect(() => {
    const nextHtml = toHtmlString(value);
    valueRef.current = nextHtml;
    const editor = editorRef.current;
    if (!editor) {
      return;
    }
    const currentHtml = toHtmlString(editor.getHtml?.());
    if (currentHtml !== nextHtml) {
      editor.setHtml(nextHtml, false);
    }
  }, [value]);

  useEffect(() => {
    editorRef.current?.setMinHeight?.(height);
  }, [height]);

  useEffect(() => {
    editorRef.current?.setMaxHeight?.(resolvedMaxHeight);
  }, [resolvedMaxHeight]);

  useImperativeHandle(ref, () => ({
    focus() {
      editorRef.current?.focus?.();
    },
    getHtml() {
      return editorRef.current?.getHtml?.() || valueRef.current;
    },
    getText() {
      return editorRef.current?.getText?.() || "";
    },
    getMarkdown() {
      return editorRef.current?.getMarkdown?.() || "";
    },
    setHtml(html, shouldEmit = false) {
      editorRef.current?.setHtml?.(toHtmlString(html), shouldEmit);
    },
    getInstance() {
      return editorRef.current;
    }
  }));

  return <div ref={hostRef} className="javaex-rich-text-editor-host" />;
});

export default RichTextEditor;

// demo/vue3-javaex-editor-demo/src/components/RichTextEditor.vue
<template>
  <div ref="editorHost" class="javaex-rich-text-editor-host"></div>
</template>

<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref, shallowRef, watch } from "vue";
import { createEditor } from "javaex-editor";

const props = defineProps({
  modelValue: {
    type: String,
    default: ""
  },
  editorId: {
    type: String,
    default: "rich-text-editor"
  },
  placeholder: {
    type: String,
    default: "请输入内容"
  },
  height: {
    type: [Number, String],
    default: 520
  },
  maxHeight: {
    type: [Number, String, null],
    default: undefined
  },
  toolbar: {
    type: Array,
    default: undefined
  },
  emojiGroups: {
    type: Array,
    default: undefined
  },
  editorOptions: {
    type: Object,
    default: () => ({})
  }
});

const emit = defineEmits(["update:modelValue", "change", "ready"]);
const editorHost = ref(null);
const editorInstance = shallowRef(null);
const htmlValue = computed(() => toHtmlString(props.modelValue));
const resolvedMaxHeight = computed(() => (props.maxHeight === undefined ? props.height : props.maxHeight));

function toHtmlString(value) {
  return value == null ? "" : String(value);
}

async function createEditorInstance() {
  if (editorInstance.value) {
    return;
  }
  await nextTick();
  if (!editorHost.value) {
    return;
  }

  const editorConfig = {
    ...props.editorOptions,
    editorId: props.editorId,
    value: htmlValue.value,
    placeholder: props.placeholder,
    height: props.height,
    maxHeight: resolvedMaxHeight.value,
    onChange(payload) {
      const html = toHtmlString(payload?.html);
      emit("update:modelValue", html);
      emit("change", payload);
    }
  };

  if (Array.isArray(props.toolbar)) {
    editorConfig.toolbar = props.toolbar;
  }
  if (Array.isArray(props.emojiGroups) && props.emojiGroups.length) {
    editorConfig.emojiGroups = props.emojiGroups;
  }

  editorInstance.value = createEditor(editorHost.value, editorConfig);
  emit("ready", editorInstance.value);
}

function destroyEditorInstance() {
  editorInstance.value?.destroy?.();
  editorInstance.value = null;
}

function syncEditorContent(value) {
  const editor = editorInstance.value;
  if (!editor) {
    return;
  }
  const nextHtml = toHtmlString(value);
  const currentHtml = toHtmlString(editor.getHtml?.());
  if (currentHtml !== nextHtml) {
    editor.setHtml(nextHtml, false);
  }
}

onMounted(createEditorInstance);
onBeforeUnmount(destroyEditorInstance);

watch(() => props.modelValue, syncEditorContent);
watch(() => props.height, (value) => {
  editorInstance.value?.setMinHeight?.(value);
});
watch(resolvedMaxHeight, (value) => {
  editorInstance.value?.setMaxHeight?.(value);
});

defineExpose({
  focus() {
    editorInstance.value?.focus?.();
  },
  getHtml() {
    return editorInstance.value?.getHtml?.() || htmlValue.value;
  },
  getText() {
    return editorInstance.value?.getText?.() || "";
  },
  getMarkdown() {
    return editorInstance.value?.getMarkdown?.() || "";
  },
  setHtml(html, shouldEmit = false) {
    editorInstance.value?.setHtml?.(toHtmlString(html), shouldEmit);
  },
  getInstance() {
    return editorInstance.value;
  }
});
</script>

<style scoped>
.javaex-rich-text-editor-host {
  width: 100%;
  min-width: 0;
}
</style>
